# This file was generated by GoReleaser. DO NOT EDIT.
cask "codesearch" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "de1c0fd689bd27b9f525bda57dd9cc78e56bcc06f1f77d3c61e7e3d2d44fce05"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "18e22d6b171a15da83884b797d6b33cf54177bc8a4319d3cb2e844c5ca800ea2"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3ce811406676fa0279db5fe175b8a3d3e73503e18316f42405486c355770605"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2914c657095d185db4c813a4531be13c5bb96760cd9031c2e1242e9b68a9dba1"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_linux_amd64.tar.gz"
    end
  end

  name "codesearch"
  desc "A free-text search tool that helps AI agents easily locate documentation and infrastructure configuration (like Helm or Terraform) across entire codebases."
  homepage "https://github.com/mjpitz/codesearch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codesearch"

  # No zap stanza required
end
