# This file was generated by GoReleaser. DO NOT EDIT.
cask "codesearch" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e53d944cd9a2f98101f7b7795284ccdf3df26347fbb4c44ad97ac74bdc0a5019"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c19615aacba75869fab257464cfc868554f28440a4cfc82211b5a3ff2d9b0d7f"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "23d6d15f7fb659fd3f2349fe58f67e1c9d570542d4d77525068df8d837e3deb0"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eff63bb68f9d44ce14f81d3b221e24c660af17f66824655e132272d1bc798673"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_linux_arm64.tar.gz"
    end
  end

  name "codesearch"
  desc "A free-text search tool that helps AI agents easily locate documentation and infrastructure configuration (like Helm or Terraform) across entire codebases."
  homepage "https://github.com/mjpitz/codesearch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codesearch"

  # No zap stanza required

end
