# This file was generated by GoReleaser. DO NOT EDIT.
cask "codesearch" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "66ad90c55b23f113900cd9e75abff1509a8bf26d6501ba25a546dc65d8266ba0"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d731116ee68c3695551b135416ede57dafc7ca707efa590cfe79ac3ba5525bb9"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f53d9c0965b3374b22e5e39bbf5ea54bf0dcab09d54d1748744af0370883b9a6"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5422bf3a2f70a031366801bdd23c10c497d05d0437778d21d923abb9d561097"
      url "https://github.com/mjpitz/codesearch/releases/download/v#{version}/codesearch_linux_amd64.tar.gz"
    end
  end

  name "codesearch"
  desc "A free-text search tool that helps AI agents easily locate documentation and infrastructure configuration (like Helm or Terraform) across entire codebases."
  homepage "https://github.com/mjpitz/codesearch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codesearch"

  # No zap stanza required
end
